# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, path: "../scripts/provision.sh"

  config.vm.define "k8master" do |k8master| 
    k8master.vm.hostname = "k8master"
    k8master.vm.network "private_network", ip: "192.168.33.10"

    k8master.vm.provider "virtualbox" do |vb|  
     # Customize the amount of memory on the VM:
     vb.memory = "8000"
     vb.name = "k8master"
   end
  end

end
