# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, path: "../scripts/provision.sh"

  config.vm.define "k8worker1" do |k8worker1| 
    k8worker1.vm.hostname = "k8worker1"
    k8worker1.vm.network "private_network", ip: "192.168.33.11"

    k8worker1.vm.provider "virtualbox" do |vb|  
     # Customize the amount of memory on the VM:
     vb.memory = "4000"
     vb.name = "k8worker1"
   end
  end
  
end
